apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: whatif-agent
  name: {{ .Values.whatifAgent.name }}
  namespace: {{ .Values.whatifAgent.namespace }}
spec:
  selector:
    matchLabels:
      component: whatif-agent
  replicas: {{ .Values.whatifAgent.replicaCount }}
  template:
    metadata:
      labels:
        component: whatif-agent
    spec:
      serviceAccountName: whatif-agent
      containers:
        - command:
            - /bin/kube-scheduler
            - --config=/etc/kubernetes/scheduler-config.yaml
          image: {{ .Values.whatifAgent.image }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 10259
              scheme: HTTPS
            initialDelaySeconds: 15
          name: whatif-agent
          readinessProbe:
            httpGet:
              path: /healthz
              port: 10259
              scheme: HTTPS
          resources:
            requests:
              cpu: "0.1"
          securityContext:
            privileged: false
          volumeMounts:
            - name: whatif-agent-config
              mountPath: /etc/kubernetes
              readOnly: true
      hostNetwork: false
      hostPID: false
      volumes:
        - name: whatif-agent-config
          configMap:
            name: whatif-agent-config
